# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Institutionalized < Formula
  desc "A CLI tool that uses LLMs to create commit and PR messages based on git status"
  homepage "https://github.com/IanKnighton/institutionalized"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/IanKnighton/institutionalized/releases/download/v0.4.2/institutionalized-0.4.2-macos-amd64.tar.gz"
      sha256 "6337abb680c1541eacd5adf5c169128fc1c0a9a4b1c24398ad6a9966b99894b0"

      def install
        bin.install "institutionalized"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/IanKnighton/institutionalized/releases/download/v0.4.2/institutionalized-0.4.2-macos-arm64.tar.gz"
      sha256 "7f86ded8be676210918370901cccc772132e8f23442165dbec3cb3a85b28746c"

      def install
        bin.install "institutionalized"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/IanKnighton/institutionalized/releases/download/v0.4.2/institutionalized-0.4.2-linux-amd64.tar.gz"
      sha256 "16d89d8a09d5ec70204c92f07c47f5780014dd016c93bfb928b8751d308d6134"
      def install
        bin.install "institutionalized"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/IanKnighton/institutionalized/releases/download/v0.4.2/institutionalized-0.4.2-linux-arm64.tar.gz"
      sha256 "dc079b9c3783ef67b09d6bab6440e947ba21a4460a2b4f060e14ae35b4cc29cb"
      def install
        bin.install "institutionalized"
      end
    end
  end

  test do
    system "#{bin}/institutionalized", "version"
  end
end
